# Generated by Django 3.0.3 on 2020-09-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pillars',
            name='body',
        ),
    ]
